POST http://127.0.0.1:8888/realms/CONTINENTAL/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=CONTINENTAL-CLIENT&username=admin&password=password&grant_type=password

> {%
    client.global.set("token", response.body.access_token);
    client.log(client.global.get("token"))
%}

### CREATE USER
< {%
    request.variables.set("token", client.global.get("token"))
%}
POST http://127.0.0.1:8080/admin/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "newuser6",
  "email": "newuser6@example.com",
  "firstName": "New",
  "lastName": "User",
  "password": "password"
}

###