### PUBLIC
## See: http-client.env.json
< {%
request.variables.set("token", client.global.get("token"))
%}
GET http://127.0.0.1:8080/public
Accept: application/json

### PRIVATE
## See: http-client.env.json
< {%
    request.variables.set("token", client.global.get("token"))
%}
GET http://127.0.0.1:8080/private
Authorization: Bearer {{token}}
Accept: application/json

### ADMIN
## See: http-client.env.json
< {%
    request.variables.set("token", client.global.get("token"))
%}
GET http://127.0.0.1:8080/admin
Authorization: Bearer {{token}}
Accept: application/json